var first_name="Ranbir";
var last_name="Kapoor";
console.log(last_name);
var full_name=first_name.concat(last_name);
console.log(full_name);
var a = 10;
var b = 5;
var add = a+b;
console.log(add);
var a = 10;
var b = 5;
var subtract = a-b;
console.log(subtract);
var a = 10;
var b = 5;
var divide = a/b;
console.log(divide);
var a = 10;
var b = 5;
var multiply = a*b;
console.log(multiply);